package com.betamedia.atom.core.api.web.form;

/**
 * Created by vsnigur on 7/17/17.
 */
public enum Country {
    AFGHANISTAN("Afghanistan","+93"),
    ALBANIA("Albania","+355"),
    AMERICAN_SAMOA("American Samoa","+1684"),
    ANDORRA("Andorra","+376"),
    ANGOLA("Angola","+244"),
    ANGUILLA("Anguilla","+1264"),
    ANTARCTICA("Antarctica","+672"),
    ANTIGUA_AND_BARBUDA("Antigua And Barbuda","+1268"),
    ARGENTINA("Argentina","+54"),
    ARMENIA("Armenia","+374"),
    ARUBA("Aruba","+297"),
    AUSTRALIA("Australia","+61"),
    AUSTRIA("Austria","+43"),
    AZERBAIJAN("Azerbaijan","+994"),
    BAHAMAS("Bahamas","+1242"),
    BAHRAIN("Bahrain","+973"),
    BANGLADESH("Bangladesh","+880"),
    BARBADOS("Barbados","+1246"),
    BELARUS("Belarus","+375"),
    BELIZE("Belize","+501"),
    BENIN("Benin","+229"),
    BERMUDA("Bermuda","+#ERROR!"),
    BHUTAN("Bhutan","+975"),
    BOLIVIA("Bolivia","+591"),
    BOSNIA_AND_HERZEGOVINA("Bosnia And Herzegovina","+387"),
    BOTSWANA("Botswana","+267"),
    BRAZIL("Brazil","+55"),
    BRUNEI_DARUSSALAM("Brunei Darussalam","+673"),
    BULGARIA("Bulgaria","+359"),
    BURKINA_FASO("Burkina Faso","+226"),
    BURUNDI("Burundi","+257"),
    CAMBODIA("Cambodia","+855"),
    CAMEROON("Cameroon","+237"),
    CAPE_VERDE("Cape Verde","+238"),
    CAYMAN_ISLANDS("Cayman Islands","+1345"),
    CENTRAL_AFRICAN_REPUBLIC("Central African Republic","+236"),
    CHAD("Chad","+235"),
    CHILE("Chile","+56"),
    CHINA("China","+86"),
    COCUS_ISLANDS("Cocus Islands","+891"),
    COLOMBIA("Colombia","+57"),
    COMOROS("Comoros","+269"),
    CONGO("Congo","+242"),
    COOK_ISLANDS("Cook Islands","+682"),
    COSTA_RICA("Costa Rica","+506"),
    COTE_DIVOIRE("Cote D'Ivoire","+225"),
    CROATIA("Croatia","+385"),
    CUBA("Cuba","+53"),
    CYPRUS("Cyprus","+357"),
    CZECH_REPUBLIC("Czech Republic","+420"),
    DENMARK("Denmark","+45"),
    DJIBOUTI("Djibouti","+253"),
    DOMINICA("Dominica","+1767"),
    DOMINICAN_REPUBLIC("Dominican Republic","+1809"),
    EGYPT("Egypt","+20"),
    EL_SALVADOR("El Salvador","+503"),
    EQUATORIAL_GUINEA("Equatorial Guinea","+240"),
    ERITREA("Eritrea","+291"),
    ESTONIA("Estonia","+372"),
    ETHIOPIA("Ethiopia","+251"),
    FALKLAND_ISLANDSMALVINAS("Falkland Islands (Malvinas)","+500"),
    FAROE_ISLANDS("Faroe Islands","+298"),
    FIJI("Fiji","+679"),
    FINLAND("Finland","+358"),
    GABON("Gabon","+241"),
    GAMBIA("Gambia","+220"),
    GEORGIA("Georgia","+995"),
    GERMANY("Germany","+49"),
    GHANA("Ghana","+233"),
    GIBRALTAR("Gibraltar","+350"),
    GREECE("Greece","+30"),
    GREENLAND("Greenland","+299"),
    GRENADA("Grenada","+1473"),
    GUAM("Guam","+1671"),
    GUATEMALA("Guatemala","+502"),
    GUINEA("Guinea","+224"),
    GUINEA_BISSAU("Guinea-Bissau","+245"),
    GUYANA("Guyana","+592"),
    HAITI("Haiti","+509"),
    HOLY_SEE("Holy See (Vatican City State)","+39"),
    HONDURAS("Honduras","+504"),
    HONG_KONG("Hong Kong","+852"),
    HUNGARY("Hungary","+36"),
    ICELAND("Iceland","+354"),
    INDIA("India","+91"),
    INDONESIA("Indonesia","+62"),
    IRAQ("Iraq","+964"),
    IRELAND("Ireland","+353"),
    ISLE_OF_MAN("Isle Of Man","+44"),
    ISRAEL("Israel","+972"),
    ITALY("Italy","+39"),
    JAMAICA("Jamaica","+1876"),
    JAPAN("Japan","+81"),
    JERSEY("Jersey","+44"),
    JORDAN("Jordan","+962"),
    KAZAKHSTAN("Kazakhstan","+7"),
    KENYA("Kenya","+254"),
    KIRIBATI("Kiribati","+686"),
    KUWAIT("Kuwait","+965"),
    KYRGYZSTAN("Kyrgyzstan","+996"),
    LAO_PEOPLE_DEMOCRATIC_REPUBLIC("Lao People'S Democratic Republic","+856"),
    LATVIA("Latvia","+371"),
    LEBANON("Lebanon","+961"),
    LESOTHO("Lesotho","+266"),
    LIBERIA("Liberia","+231"),
    LIBYAN_ARAB_JAMAHIRIYA("Libyan Arab Jamahiriya","+218"),
    LIECHTENSTEIN("Liechtenstein","+423"),
    LITHUANIA("Lithuania","+370"),
    LUXEMBOURG("Luxembourg","+352"),
    MACAO("Macao","+853"),
    MACEDONIA("Macedonia","+389"),
    MADAGASCAR("Madagascar","+261"),
    MALAWI("Malawi","+265"),
    MALAYSIA("Malaysia","+60"),
    MALDIVES("Maldives","+960"),
    MALI("Mali","+223"),
    MALTA("Malta","+356"),
    MARSHALL_ISLANDS("Marshall Islands","+692"),
    MAURITANIA("Mauritania","+222"),
    MAURITIUS("Mauritius","+230"),
    MEXICO("Mexico","+52"),
    MOLDOVA("Moldova","+373"),
    MONACO("Monaco","+377"),
    MONGOLIA("Mongolia","+976"),
    MONTENEGRO("Montenegro (Crna Gora)","+382"),
    MONTSERRAT("Montserrat","+1664"),
    MOZAMBIQUE("Mozambique","+258"),
    NAMIBIA("Namibia","+264"),
    NAURU("Nauru","+674"),
    NEPAL("Nepal","+977"),
    NETHERLANDS("Netherlands","+31"),
    NETHERLANDS_ANTILLES("Netherlands Antilles","+599"),
    NEW_ZEALAND("New Zealand","+64"),
    NICARAGUA("Nicaragua","+505"),
    NIGER("Niger","+227"),
    NIGERIA("Nigeria","+234"),
    NIUE("Niue","+683"),
    NORTHERN_MARIANA_ISLANDS("Northern Mariana Islands","+1670"),
    NORWAY("Norway","+47"),
    OMAN("Oman","+968"),
    PAKISTAN("Pakistan","+92"),
    PALAU("Palau","+680"),
    PAPUA_NEW_GUINEA("Papua New Guinea","+675"),
    PARAGUAY("Paraguay","+595"),
    PERU("Peru","+51"),
    PHILIPPINES("Philippines","+63"),
    PITCAIRN("Pitcairn","+870"),
    POLAND("Poland","+48"),
    PORTUGAL("Portugal","+351"),
    PUERTO_RICO("Puerto Rico","+1"),
    QATAR("Qatar","+974"),
    ROMANIA("Romania","+40"),
    RUSSIAN_FEDERATION("Russian Federation","+7"),
    RWANDA("Rwanda","+250"),
    SAINT_HELENA("Saint Helena","+290"),
    SAINT_KITTS_AND_NEVIS("Saint Kitts And Nevis","+1869"),
    SAINT_LUCIA("Saint Lucia","+1758"),
    SAINT_VINCENT_AND_THE_GRENADINES("Saint Vincent And The Grenadines","+1784"),
    SAMOA("Samoa","+685"),
    SAN_MARINO("San Marino","+378"),
    SAO_TOME_AND_PRINCIPE("Sao Tome And Principe","+239"),
    SAUDI_ARABIA("Saudi Arabia","+966"),
    SENEGAL("Senegal","+221"),
    SEYCHELLES("Seychelles","+248"),
    SIERRA_LEONE("Sierra Leone","+232"),
    SERBIA("Serbia (Србија)","+381"),
    SINGAPORE("Singapore","+65"),
    SLOVAKIA("Slovakia","+421"),
    SLOVENIA("Slovenia","+386"),
    SOLOMON_ISLANDS("Solomon Islands","+677"),
    SOMALIA("Somalia","+252"),
    SOUTH_AFRICA("South Africa","+27"),
    SOUTH_KOREA("South Korea","+82"),
    SPAIN("Spain","+34"),
    SRI_LANKA("Sri Lanka","+94"),
    SUDAN("Sudan","+249"),
    SURINAME("Suriname","+597"),
    SWAZILAND("Swaziland","+268"),
    SWEDEN("Sweden","+46"),
    SWITZERLAND("Switzerland","+41"),
    SYRIAN_ARAB_REPUBLIC("Syrian Arab Republic","+963"),
    TAIWAN("Taiwan","+886"),
    TAJIKISTAN("Tajikistan","+992"),
    TANZANIA("Tanzania","+255"),
    THAILAND("Thailand","+66"),
    TIMOR_LESTE("Timor-Leste","+670"),
    TOGO("Togo","+228"),
    TOKELAU("Tokelau","+690"),
    TONGA("Tonga","+676"),
    TRINIDAD_AND_TOBAGO("Trinidad And Tobago","+1868"),
    TURKEY("Turkey","+90"),
    TURKMENISTAN("Turkmenistan","+993"),
    TURKS_AND_CAICOS_ISLANDS("Turks And Caicos Islands","+1649"),
    TUVALU("Tuvalu","+688"),
    UGANDA("Uganda","+256"),
    UKRAINE("Ukraine","+380"),
    UNITED_ARAB_EMIRATES("United Arab Emirates","+971"),
    UNITED_KINGDOM("United Kingdom","+44"),
    URUGUAY("Uruguay","+598"),
    UZBEKISTAN("Uzbekistan","+998"),
    VANUATU("Vanuatu","+678"),
    VENEZUELA("Venezuela","+58"),
    VIET_NAM("Viet Nam","+84"),
    YEMEN("Yemen","+967"),
    ZAMBIA("Zambia","+260"),
    ZIMBABWE("Zimbabwe","+263");

    private String name;
    private String phonePrefix;

    Country(String name, String phonePrefix) {
        this.name = name;
        this.phonePrefix = phonePrefix;
    }

    public String getPhonePrefix() {
        return phonePrefix;
    }

    public String getName() {
        return name;
    }

}
